# Generated by Django 5.1.4 on 2026-06-27 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('protocols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado'), ('period_closed', 'Período cerrado'), ('pdf_generated', 'PDF generado'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, help_text='Tipo de objeto afectado (ej: Expense, ExpensePeriod)', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='Representación textual del objeto en el momento del evento', max_length=500)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento en formato JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej: 'Período Q1 2025'", max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('exported', 'Exportado')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_created', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_periods', to='protocols.protocol')),
            ],
            options={
                'verbose_name': 'Período de rendición',
                'verbose_name_plural': 'Períodos de rendición',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transporte'), ('meals', 'Comidas'), ('accommodation', 'Alojamiento'), ('other', 'Otro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('expense_date', models.DateField(help_text='Fecha del gasto según el ticket')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('vendor', models.CharField(blank=True, help_text='Nombre del comercio o proveedor', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado')], default='pending', max_length=20)),
                ('ocr_raw_data', models.JSONField(blank=True, help_text='Datos crudos del OCR', null=True)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Confianza del OCR (0-1)', null=True)),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_submitted', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='patients.visit')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expenseperiod')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Foto o scan del ticket', upload_to='tickets/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_task_id', models.CharField(blank=True, help_text='ID de la tarea Celery de OCR', max_length=100)),
                ('ocr_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_files', to='expenses.expense')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de ticket',
                'verbose_name_plural': 'Archivos de ticket',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
