# Generated by Django 5.1.4 on 2026-06-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado'), ('ocr_completed', 'OCR completado'), ('ocr_failed', 'OCR fallido'), ('period_closed', 'Período cerrado'), ('pdf_generated', 'PDF generado'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='Confianza global del OCR (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ocr_raw_data',
            field=models.JSONField(blank=True, help_text='Datos del OCR (extracted + confidence)', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('ocr_pending', 'Procesando OCR'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado')], default='ocr_pending', max_length=20),
        ),
    ]
