# Generated by Django 5.1.4 on 2026-06-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_ocr_fields_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfile',
            name='file',
            field=models.FileField(help_text='Foto o scan del ticket (imagen o PDF)', upload_to='tickets/%Y/%m/'),
        ),
    ]
