# Generated by Django 5.1.4 on 2026-06-27 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_ticket_filefield_pdf_support'),
        ('protocols', '0002_site_model_and_protocol_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto convertido a USD para control contra budget.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate_to_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de moneda original equivalente a 1 USD. Ej: ARS por USD.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado'), ('corrected', 'Corregido'), ('exported', 'Exportado'), ('ocr_completed', 'OCR completado'), ('ocr_failed', 'OCR fallido'), ('period_closed', 'Período cerrado'), ('pdf_generated', 'PDF generado'), ('reception_uploaded', 'Ticket subido en recepción'), ('reception_assigned', 'Ticket imputado'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('ocr_pending', 'Procesando OCR'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado'), ('settled', 'Liquidado'), ('exported', 'Exportado')], default='ocr_pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReceptionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Foto o scan del ticket recibido en recepción', upload_to='reception_tickets/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending_assignment', 'Pendiente de imputación'), ('assigned', 'Imputado'), ('discarded', 'Descartado')], default='pending_assignment', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_ticket', to='expenses.expense')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_tickets', to='protocols.site')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_tickets_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de recepción',
                'verbose_name_plural': 'Tickets de recepción',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transporte'), ('meals', 'Comidas'), ('accommodation', 'Alojamiento'), ('other', 'Otro')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Monto máximo permitido en USD', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items_created', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='protocols.protocol')),
                ('visit_type', models.ForeignKey(blank=True, help_text='Si queda vacío aplica a todas las visitas del protocolo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='protocols.visittype')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'ordering': ['protocol__code', 'category', 'visit_type__order'],
                'unique_together': {('protocol', 'visit_type', 'category')},
            },
        ),
    ]
