# Generated by Django 5.1.4 on 2026-07-09 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_amount_usd_expense_exchange_rate_to_usd_and_more'),
        ('patients', '0002_patient_viatic_cap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('observed', 'Observado'), ('corrected', 'Corregido'), ('exported', 'Exportado'), ('sent_to_coordinator', 'Enviado al coordinador'), ('ocr_completed', 'OCR completado'), ('ocr_failed', 'OCR fallido'), ('period_closed', 'Período cerrado'), ('pdf_generated', 'PDF generado'), ('reception_uploaded', 'Ticket subido en recepción'), ('reception_assigned', 'Ticket imputado'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='auditlog_object_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='auditlog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expense_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expense_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'expense_date'], name='expense_status_date_idx'),
        ),
    ]
