# Generated by Django 5.1.4 on 2026-06-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
        ('protocols', '0002_site_model_and_protocol_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site de investigación al que pertenece este usuario (multisite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='protocols.site'),
        ),
    ]
