# Generated by Django 5.1.4 on 2026-06-27 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(help_text='Código de identificación del paciente. Ej: 001-001', max_length=50)),
                ('initials', models.CharField(blank=True, help_text='Iniciales del paciente (referencia interna, no identificatorias)', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_patient_id', models.CharField(blank=True, help_text='ID en Alpha CR para futura integración', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='protocols.protocol')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['protocol', 'patient_code'],
                'unique_together': {('protocol', 'patient_code')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada'), ('missed', 'No asistió')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_visit_id', models.CharField(blank=True, help_text='ID en Alpha CR para futura integración', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='protocols.visittype')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
