# Generated by Django 5.1.4 on 2026-07-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0005_alter_auditlog_action_auditlog_auditlog_object_idx_and_more'),
        ('protocols', '0002_site_model_and_protocol_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('phone', models.CharField(help_text="Número internacional sin '+', tal como lo reporta Meta. Ej: 5493511234567", max_length=30, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(help_text='Site al que se imputan los tickets recibidos de este número', on_delete=django.db.models.deletion.CASCADE, related_name='channel_contacts', to='protocols.site')),
            ],
            options={
                'verbose_name': 'Contacto de canal',
                'verbose_name_plural': 'Contactos de canal',
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('external_id', models.CharField(help_text='ID del mensaje en el canal (wamid...) para no procesar dos veces', max_length=200, unique=True)),
                ('sender', models.CharField(blank=True, max_length=30)),
                ('message_type', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processed', 'Procesado'), ('ignored', 'Ignorado'), ('failed', 'Fallido')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reception_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='expenses.receptionticket')),
            ],
            options={
                'verbose_name': 'Mensaje entrante',
                'verbose_name_plural': 'Mensajes entrantes',
                'ordering': ['-received_at'],
            },
        ),
    ]
