# Generated by Django 5.1.4 on 2026-06-27 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='ARS', help_text='ISO 4217', max_length=3)),
                ('max_daily_meals', models.DecimalField(blank=True, decimal_places=2, help_text='Tope diario para comidas en la moneda del protocolo', max_digits=10, null=True)),
                ('max_daily_transport', models.DecimalField(blank=True, decimal_places=2, help_text='Tope diario para transporte', max_digits=10, null=True)),
                ('max_daily_accommodation', models.DecimalField(blank=True, decimal_places=2, help_text='Tope diario para alojamiento', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_protocol_id', models.CharField(blank=True, help_text='ID en Alpha CR para futura integración', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('window_before_days', models.PositiveIntegerField(default=3, help_text='Días antes de la visita en que se aceptan tickets')),
                ('window_after_days', models.PositiveIntegerField(default=3, help_text='Días después de la visita en que se aceptan tickets')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_types', to='protocols.protocol')),
            ],
            options={
                'verbose_name': 'Tipo de visita',
                'verbose_name_plural': 'Tipos de visita',
                'ordering': ['order'],
                'unique_together': {('protocol', 'code')},
            },
        ),
    ]
