# Generated by Django 5.1.4 on 2026-06-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: CINME-01', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Argentina', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site de investigación',
                'verbose_name_plural': 'Sites de investigación',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='protocol',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site de investigación donde se ejecuta este protocolo (multi-site futuro)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='protocols.site'),
        ),
    ]
